<?php

/**
 * @file
 * local_actions.theme
 */

/**
 * Local actions preprocess.
 */
function gin_preprocess_menu_local_action(&$variables) {
  $variables['link']['#options']['attributes']['class'][] = 'button--primary';
  $variables['attributes']['class'][] = 'local-actions__item';
  $legacy_class_key = array_search('button-action', $variables['link']['#options']['attributes']['class']);

  if ($legacy_class_key !== FALSE) {
    $variables['link']['#options']['attributes']['class'][$legacy_class_key] = 'button--action';
  }

  // Are we displaying an edit form?
  if (_gin_form_actions()) {
    $classes = &$variables['link']['#options']['attributes']['class'];
    $classes = array_filter($classes, function ($e) {
      return $e != 'button--primary';
    });
  }
}
