<?php

/**
 * @file
 * theme.theme
 */

use Drupal\gin\GinContentFormHelper;

/**
 * Implements page_alter().
 */
function gin_theme_suggestions_page_alter(&$suggestions, $variables) {
  $path = \Drupal::requestStack()->getCurrentRequest()->getPathInfo();

  if ($path != '/') {
    $path = trim($path, '/');
    $arg = str_replace(["/", '-'], ['_', '_'], $path);
    $suggestions[] = 'page__' . $arg;
  }

  // The node page template is required to use the node content form.
  if (\Drupal::classResolver(GinContentFormHelper::class)->isContentForm()
    && !in_array('page__node', $suggestions)) {
    $suggestions[] = 'page__node';
  }
}

/**
 * Implements top_bar_alter().
 */
function gin_theme_suggestions_top_bar_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'top_bar__gin';
}

/**
 * Implements form_alter().
 */
function gin_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'form__' . str_replace('-', '_', $variables['element']['#id']);
}

/**
 * Implements table_alter().
 */
function gin_theme_suggestions_table_alter(array &$suggestions, array $variables): void {
  if (empty($variables['attributes']['class'])) {
    return;
  }

  if (is_array($variables['attributes']['class']) && in_array('field-multiple-table', $variables['attributes']['class'])) {
    $suggestions[] = 'table__simple';
  }
}

/**
 * Implements views_view_field_alter() for status field.
 */
function gin_theme_suggestions_views_view_field_alter(array &$suggestions, array $variables) {
  $field_name = $variables['field']->field;
  if ($field_name == 'status') {
    $suggestions[] = 'views_view_field__' . $field_name;
  }
}
