<?php

/**
 * @file
 * toolbar.theme
 */

use Drupal\gin\GinUserPicture;

/**
 * Implements toolbar preprocess.
 *
 * This is also called by system_preprocess_toolbar() in instances where Gin
 * is the admin theme but not the active theme.
 *
 * @see system_preprocess_toolbar()
 */
function gin_preprocess_toolbar(&$variables) {
  $variables['attributes']['data-drupal-gin-processed-toolbar'] = TRUE;

  // The controller resolver does not support Closures at this time. For now,
  // we use a wrapper function to load the service with dependencies.
  // @see https://www.drupal.org/project/drupal/issues/3060638
  $variables['user_picture'] = [
    '#lazy_builder' => [
      GinUserPicture::class . '::build',
      [],
    ],
    '#create_placeholder' => TRUE,
  ];

  // Check if Navigation module is active.
  if (_gin_module_is_active('navigation')) {
    // Attach the new drupal navigation styles.
    $variables['#attached']['library'][] = 'gin/navigation';
    return;
  }

  // Toolbar library.
  $variables['#attached']['library'][] = 'gin/toolbar';
}
